laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index')->name('home');

    Route::post('empresas/get_ciudades', 'EmpresasController@getCiudades');
    Route::resource('empresas', 'EmpresasController');

    /* Administración de productos */
    Route::get('empresas/{id}/productos', [
        'uses' => 'ProductosController@index',
        'as' => 'empresas.productos.index'
    ]);

    Route::get('empresas/{id}/productos/create', [
        'uses' => 'ProductosController@create',
        'as' => 'empresas.productos.create'
    ]);
    Route::post('empresas/productos/store', [
        'uses' => 'ProductosController@store',
        'as' => 'empresas.productos.store'
    ]);

    Route::get('empresas/productos/{id}/edit', [
        'uses' => 'ProductosController@edit',
        'as' => 'empresas.productos.edit'
    ]);
    Route::patch('empresas/productos/{id}/update', [
        'uses' => 'ProductosController@update',
        'as' => 'empresas.productos.update'
    ]);

    Route::delete('empresas/productos/{id}', [
        'uses' => 'ProductosController@destroy',
        'as' => 'empresas.productos.destroy'
    ]);
    /* Fin administración de productos */

    /* --------------------------------------------- */

    /* Administración de clientes */
    Route::get('empresas/{id}/clientes', [
        'uses' => 'ClientesController@index',
        'as' => 'empresas.clientes.index'
    ]);

    Route::get('empresas/{id}/clientes/create', [
        'uses' => 'ClientesController@create',
        'as' => 'empresas.clientes.create'
    ]);
    Route::post('empresas/clientes/store', [
        'uses' => 'ClientesController@store',
        'as' => 'empresas.clientes.store'
    ]);

    Route::get('empresas/clientes/{id}/edit', [
        'uses' => 'ClientesController@edit',
        'as' => 'empresas.clientes.edit'
    ]);
    Route::patch('empresas/clientes/{id}/update', [
        'uses' => 'ClientesController@update',
        'as' => 'empresas.clientes.update'
    ]);

    Route::delete('empresas/clientes/{id}', [
        'uses' => 'ClientesController@destroy',
        'as' => 'empresas.clientes.destroy'
    ]);
    /* Fin administración de clientes */

    /* Administración de procesos */
    Route::get('empresas/{id}/procesos', [
        'uses' => 'ProcesosController@index',
        'as' => 'empresas.procesos.index'
    ]);

    Route::get('empresas/{id}/procesos/create', [
        'uses' => 'ProcesosController@create',
        'as' => 'empresas.procesos.create'
    ]);
    Route::post('empresas/procesos/store', [
        'uses' => 'ProcesosController@store',
        'as' => 'empresas.procesos.store'
    ]);

    Route::get('empresas/procesos/{id}/edit', [
        'uses' => 'ProcesosController@edit',
        'as' => 'empresas.procesos.edit'
    ]);
    Route::patch('empresas/procesos/{id}/update', [
        'uses' => 'ProcesosController@update',
        'as' => 'empresas.procesos.update'
    ]);

    Route::delete('empresas/procesos/{id}', [
        'uses' => 'ProcesosController@destroy',
        'as' => 'empresas.procesos.destroy'
    ]);
    /* Fin administración de procesos */

    /* Administración de problemáticas */
    Route::get('empresas/{id}/problematicas', [
        'uses' => 'ProblematicasController@index',
        'as' => 'empresas.problematicas.index'
    ]);

    Route::get('empresas/{id}/problematicas/create', [
        'uses' => 'ProblematicasController@create',
        'as' => 'empresas.problematicas.create'
    ]);
    Route::post('empresas/problematicas/store', [
        'uses' => 'ProblematicasController@store',
        'as' => 'empresas.problematicas.store'
    ]);

    Route::get('empresas/problematicas/{id}/edit', [
        'uses' => 'ProblematicasController@edit',
        'as' => 'empresas.problematicas.edit'
    ]);
    Route::patch('empresas/problematicas/{id}/update', [
        'uses' => 'ProblematicasController@update',
        'as' => 'empresas.problematicas.update'
    ]);

    Route::delete('empresas/problematicas/{id}', [
        'uses' => 'ProblematicasController@destroy',
        'as' => 'empresas.problematicas.destroy'
    ]);
    /* Fin administración de problemáticas */

    /* Administración de proyectos */
    Route::get('empresas/{id}/proyectos', [
        'uses' => 'ProyectosController@index',
        'as' => 'empresas.proyectos.index'
    ]);

    Route::get('empresas/{id}/proyectos/create', [
        'uses' => 'ProyectosController@create',
        'as' => 'empresas.proyectos.create'
    ]);
    Route::post('empresas/proyectos/store', [
        'uses' => 'ProyectosController@store',
        'as' => 'empresas.proyectos.store'
    ]);

    Route::get('empresas/proyectos/{id}/edit', [
        'uses' => 'ProyectosController@edit',
        'as' => 'empresas.proyectos.edit'
    ]);
    Route::patch('empresas/proyectos/{id}/update', [
        'uses' => 'ProyectosController@update',
        'as' => 'empresas.proyectos.update'
    ]);

    Route::delete('empresas/proyectos/{id}', [
        'uses' => 'ProyectosController@destroy',
        'as' => 'empresas.proyectos.destroy'
    ]);

    //Tareas
    Route::get('empresas/proyectos/{id}/tareas', [
        'uses' => 'ProyectosController@tareas',
        'as' => 'empresas.proyectos.tareas.index'
    ]);

    Route::get('empresas/proyectos/tareas/{id}/', [
        'uses' => 'ProyectosController@verTarea',
        'as' => 'empresas.proyectos.tareas.show'
    ]);

    Route::get('empresas/proyectos/{id}/tareas/create', [
        'uses' => 'ProyectosController@agregarTarea',
        'as' => 'empresas.proyectos.tareas.create'
    ]);
    Route::post('empresas/proyectos/tareas/store', [
        'uses' => 'ProyectosController@guardarTarea',
        'as' => 'empresas.proyectos.tareas.store'
    ]);

    Route::get('empresas/proyectos/tareas/{id}/edit', [
        'uses' => 'ProyectosController@editarTarea',
        'as' => 'empresas.proyectos.tareas.edit'
    ]);

    Route::patch('empresas/proyectos/tareas/{id}/update', [
        'uses' => 'ProyectosController@actualizarTarea',
        'as' => 'empresas.proyectos.tareas.update'
    ]);

    Route::delete('empresas/proyectos/tareas/{id}/', [
        'uses' => 'ProyectosController@eliminarTarea',
        'as' => 'empresas.proyectos.tareas.delete'
    ]);

    //Objetivos
    Route::get('empresas/proyectos/{id}/objetivos/create', [
        'uses' => 'ProyectosController@agregarObjetivo',
        'as' => 'empresas.proyectos.objetivos.create'
    ]);
    Route::post('empresas/proyectos/objetivos/store', [
        'uses' => 'ProyectosController@guardarObjetivo',
        'as' => 'empresas.proyectos.objetivos.store'
    ]);

    Route::get('empresas/proyectos/objetivos/{id}/edit', [
        'uses' => 'ProyectosController@editarObjetivo',
        'as' => 'empresas.proyectos.objetivos.edit'
    ]);

    Route::patch('empresas/proyectos/objetivos/{id}/update', [
        'uses' => 'ProyectosController@actualizarObjetivo',
        'as' => 'empresas.proyectos.objetivos.update'
    ]);

    Route::delete('empresas/proyectos/objetivos/{id}/', [
        'uses' => 'ProyectosController@eliminarObjetivo',
        'as' => 'empresas.proyectos.objetivos.destroy'
    ]);

    //Seguimiento
    Route::get('empresas/proyectos/{id}/seguimiento', [
        'uses' => 'ProyectosController@seguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.index'
    ]);
    Route::get('empresas/proyectos/objetivos/{id}/seguimiento/create', [
        'uses' => 'ProyectosController@agregarSeguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.create'
    ]);
    Route::post('empresas/proyectos/objetivos/seguimiento/store', [
        'uses' => 'ProyectosController@guardarSeguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.store'
    ]);

    Route::get('empresas/proyectos/objetivos/seguimiento/{id}/edit', [
        'uses' => 'ProyectosController@editarSeguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.edit'
    ]);

    Route::patch('empresas/proyectos/objetivos/seguimiento/{id}/update', [
        'uses' => 'ProyectosController@actualizarSeguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.update'
    ]);

    Route::delete('empresas/proyectos/objetivos/seguimiento/{id}/', [
        'uses' => 'ProyectosController@eliminarSeguimiento',
        'as' => 'empresas.proyectos.objetivos.seguimiento.destroy'
    ]);

    /* Fin administración de proyectos */
});

laravel/app/Http/Controllers/EmpresasController.php
<?php

namespace App\Http\Controllers;

use App\Repo\Readers\EmpresasReader;
use App\Repo\Readers\ProductosReader;
use App\Repo\Writers\EmpresasWriter;
use Illuminate\Http\Request;

class EmpresasController extends Controller
{
    protected $reader;

    public function __construct(EmpresasReader $reader)
    {
        $this->reader = $reader;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empresas = $this->reader->all();
        return view('empresas.index', compact('empresas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $empresa = $this->reader->newItem();
        $provincias = $this->reader->getProvincias();
        return view('empresas.create', compact('empresa', 'provincias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'razon_social' => 'required',
            'ciudad_id' => 'required|exists:ciudades,id',
            'direccion' => 'required',
        ]);

        $empresasWriter = new EmpresasWriter($this->reader->newItem(), $request);
        if(!$empresasWriter->save())
            return redirect()->back()->withInput()->withErrors($empresasWriter->getErrors());
        return redirect()->route('empresas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $empresa = $this->reader->findItem($id);
        return view('empresas.show', compact('empresa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empresa = $this->reader->findItem($id);
        $provincias = $this->reader->getProvincias();
        $ciudades = $this->reader->getCiudades($empresa->ciudad->provincia->id);
        return view('empresas.edit', compact('empresa', 'provincias', 'ciudades'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nombre' => 'required',
            'razon_social' => 'required',
            'ciudad_id' => 'required|exists:ciudades,id',
            'direccion' => 'required',
        ]);

        $empresasWriter = new EmpresasWriter($this->reader->findItem($id), $request);
        if(!$empresasWriter->save())
            return redirect()->back()->withInput()->withErrors($empresasWriter->getErrors());
        return redirect()->route('empresas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //TODO Hacer Destroy en Cascada
    }

    public function getCiudades(Request $request){
        if (!$request->ajax()) redirect()->to('empresas');

        $ciudades = $this->reader->getCiudades($request->input('id'));

        return response()->json(['ciudades' => $ciudades]);
    }

}

laravel/resources/views/empresas/create.blade.php
@extends('layouts.app')

@section('app-content')
    <div class="md-title"><h1>Agregar empresa</h1></div>
    {!! Form::model($empresa, ['route' => 'empresas.store', 'method' => 'POST', 'role' => 'form']) !!}
        @include('layouts.alerts')
        @include('empresas.fields')
    {!! Form::close() !!}
@endsection

laravel/resources/views/empresas/edit.blade.php
@extends('layouts.app')

@section('app-content')
    <div class="md-title"><h1>Editar empresa</h1></div>
    {!! Form::model($empresa, ['route' => ['empresas.update', $empresa->id], 'method' => 'PATCH', 'role' => 'form']) !!}
        @include('layouts.alerts')
        @include('empresas.fields')
    {!! Form::close() !!}
@endsection

laravel/resources/views/empresas/fields.blade.php
<div id="empresas" class="row">
    <div class="row">
        <div class="input-field col s12">
            {{ Form::text('nombre', $empresa->nombre, ['class' => 'validate']) }}
            <label for="nombre">Nombre</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            {{ Form::text('razon_social', $empresa->razon_social, ['class' => 'validate']) }}
            <label for="nombre">Razón social</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            {{ Form::select('provincia', $provincias, null, ['id' => 'provincia-selector', 'class' => 'validate', 'placeholder' => 'Provincia']) }}
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            @if(!$empresa->id)
                {{ Form::select('ciudad_id', [], null, ['id' => 'ciudad-selector', 'class' => 'validate', 'placeholder' => 'Ciudad']) }}
            @else
                {{ Form::select('ciudad_id', $ciudades, $empresa->ciudad_id, ['id' => 'ciudad-selector', 'class' => 'validate', 'placeholder' => 'Ciudad']) }}
            @endif
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            {{ Form::text('direccion', $empresa->direccion, ['class' => 'validate']) }}
            <label for="nombre">Dirección</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            {{ Form::textarea('mision', $empresa->mision, ['class' => 'validate materialize-textarea']) }}
            <label for="nombre">Misión</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12">
            {{ Form::textarea('vision', $empresa->vision, ['class' => 'validate materialize-textarea']) }}
            <label for="nombre">Visión</label>
        </div>
    </div>

    <button type="submit" class="waves-effect waves-light btn">Guardar</button> - <a href="{{ route('empresas.index') }}">Cancelar</a>
</div>

@section('custom-js')
    <script>
        $(document).ready(function() {
            @if($empresa->id)
                $('#provincia-selector').val('{{ $empresa->ciudad->provincia->id }}');
                $('#ciudad-selector').val('{{ $empresa->ciudad->id }}');
            @endif

            $('select').material_select();
        });
    </script>
@endsection

laravel/resources/views/empresas/index.blade.php
@extends('layouts.app')

@section('app-content')

    <div id="empresas" class="row">
        <h2>Empresas</h2>
        <a class="waves-effect waves-light btn" href="{{ route('empresas.create') }}"><i class="material-icons">add</i> Agregar empresa</a>
        <table class="striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Razón Social</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
            @foreach($empresas as $empresa)
                <tr>
                    <td><a href="{{ route('empresas.show', ['id' => $empresa->id]) }}">{{ $empresa->nombre }}</a></td>
                    <td><a href="{{ route('empresas.show', ['id' => $empresa->id]) }}">{{ $empresa->razon_social }}</a></td>
                    <td>
                        <a href="{{ route('empresas.edit', ['id' => $empresa->id]) }}" class="edit"><i class="material-icons">edit</i></a>
                        <a href="{{ route('empresas.productos.index', ['id' => $empresa->id]) }}" title="Productos"><i class="material-icons">shopping_cart</i></a>
                        <a href="{{ route('empresas.clientes.index', ['id' => $empresa->id]) }}" title="Clientes"><i class="material-icons">person</i></a>
                        <a href="{{ route('empresas.procesos.index', ['id' => $empresa->id]) }}" title="Procesos"><i class="material-icons">device_hub</i></a>
                        <a href="{{ route('empresas.problematicas.index', ['id' => $empresa->id]) }}" title="Problemáticas"><i class="material-icons">error</i></a>
                        <a href="{{ route('empresas.proyectos.index', ['id' => $empresa->id]) }}" title="Proyectos"><i class="material-icons">work</i></a>
                        <a href="{{ route('empresas.destroy', ['id' => $empresa->id]) }}" class="remove"><i class="material-icons">delete</i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection

laravel/resources/views/empresas/show.blade.php
@extends('layouts.app')

@section('app-content')

    <div id="empresas" class="row">
        <h2><i class="material-icons">business</i> {{ $empresa->nombre }}</h2>
        <p><a href="{{ route('empresas.edit', ['id' => $empresa->id]) }}" class="edit"><i class="material-icons">edit</i> Editar empresa</a> - <a href="{{ url('empresas') }}" class="edit"><i class="material-icons">undo</i> Volver</a></p>
        <div class="row">
            <p><u>Nombre:</u> {{ $empresa->nombre }}</p>
            <p><u>Razón social:</u> {{ $empresa->razon_social }}</p>
            <p><u>Dirección:</u> {{ $empresa->direccion }}, {{ $empresa->ciudad->nombre }}, {{ $empresa->ciudad->provincia->nombre }}</p>
            <p><u>Misión:</u> {{ $empresa->mision }}</p>
            <p><u>Visión:</u> {{ $empresa->vision }}</p>
        </div>

        <hr>

        <div class="row">
            <h4><i class="material-icons">shopping_cart</i> Productos</h4>
            <ul>
                @foreach($empresa->productos as $producto)
                    <li>{{ $producto->nombre }}</li>
                @endforeach
            </ul>
        </div>

        <hr>

        <div class="row">
            <h4><i class="material-icons">person</i> Clientes</h4>
            <ul>
                @foreach($empresa->clientes as $cliente)
                    <li>{{ $cliente->nombre }}</li>
                @endforeach
            </ul>
        </div>

        <hr>

        <div class="row">
            <h4><i class="material-icons">device_hub</i> Procesos</h4>
            <ul>
                @foreach($empresa->procesos as $proceso)
                    <li>{{ $proceso->nombre }}</li>
                @endforeach
            </ul>
        </div>

        <hr>

        <div class="row">
            <h4><i class="material-icons">error</i> Problemáticas</h4>
            <ul>
                @foreach($empresa->problematicas as $problematica)
                    <li>{{ $problematica->nombre }}</li>
                @endforeach
            </ul>
        </div>

        <hr>

        <div class="row">
            <h4><i class="material-icons">work</i> Proyectos</h4>
            <ul>
                @foreach($empresa->proyectos as $proyecto)
                    <li>{{ $proyecto->nombre }}</li>
                @endforeach
            </ul>
        </div>

    </div>

@endsection